<a href="https://colab.research.google.com/github/Renata-Thomazelli/mentoria2021/blob/main/Copy_of_sample_wheat_knoema.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install knoema

Requirement already satisfied: knoema in /usr/local/lib/python3.7/dist-packages (1.2.38)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from knoema) (1.1.5)
Requirement already satisfied: python-csv in /usr/local/lib/python3.7/dist-packages (from knoema) (0.0.13)
Requirement already satisfied: pytest-shutil in /usr/local/lib/python3.7/dist-packages (from knoema) (1.7.0)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas->knoema) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas->knoema) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->knoema) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->knoema) (1.15.0)
Requirement already satisfied: termcolor in /usr/local/lib/python3.7/dist-packages (from pytest-shutil->knoema) (1.1.0)
Requirement already satisfied: contextlib2 in /usr/local/lib/python3.7/dist-packages (from pytest-shutil->knoema) (0.5.5)
Requirement already satisfied: path.py in /usr/local/lib/python3.7/dist-packages (from pytest-shutil->knoema) (12.5.0)
Requirement already satisfied: mock in /usr/local/lib/python3.7/dist-packages (from pytest-shutil->knoema) (4.0.3)
Requirement already satisfied: execnet in /usr/local/lib/python3.7/dist-packages (from pytest-shutil->knoema) (1.9.0)
Requirement already satisfied: pytest in /usr/local/lib/python3.7/dist-packages (from pytest-shutil->knoema) (3.6.4)
Requirement already satisfied: path in /usr/local/lib/python3.7/dist-packages (from path.py->pytest-shutil->knoema) (16.2.0)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from pytest->pytest-shutil->knoema) (8.8.0)
Requirement already satisfied: pluggy<0.8,>=0.5 in /usr/local/lib/python3.7/dist-packages (from pytest->pytest-shutil->knoema) (0.7.1)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from pytest->pytest-shutil->knoema) (1.10.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from pytest->pytest-shutil->knoema) (21.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from pytest->pytest-shutil->knoema) (57.4.0)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.7/dist-packages (from pytest->pytest-shutil->knoema) (1.4.0)
Requirement already satisfied: leven in /usr/local/lib/python3.7/dist-packages (from python-csv->knoema) (1.0.4)
Requirement already satisfied: demjson in /usr/local/lib/python3.7/dist-packages (from python-csv->knoema) (2.2.4)
Requirement already satisfied: xlrd in /usr/local/lib/python3.7/dist-packages (from python-csv->knoema) (1.1.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from python-csv->knoema) (3.2.2)
Requirement already satisfied: jtutils in /usr/local/lib/python3.7/dist-packages (from python-csv->knoema) (0.0.8)
Requirement already satisfied: xmltodict in /usr/local/lib/python3.7/dist-packages (from python-csv->knoema) (0.12.0)
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from jtutils->python-csv->knoema) (4.6.3)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from jtutils->python-csv->knoema) (2.23.0)
Requirement already satisfied: selenium in /usr/local/lib/python3.7/dist-packages (from jtutils->python-csv->knoema) (3.141.0)
Requirement already satisfied: nose in /usr/local/lib/python3.7/dist-packages (from leven->python-csv->knoema) (1.3.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->python-csv->knoema) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->python-csv->knoema) (1.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->python-csv->knoema) (2.4.7)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->jtutils->python-csv->knoema) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->jtutils->python-csv->knoema) (2021.5.30)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->jtutils->python-csv->knoema) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->jtutils->python-csv->knoema) (2.10)
Installing collected packages: argparse
Successfully installed argparse-1.4.0

In [2]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import knoema

knoema.get('USDAPSD2021May25', frequency='A', Country='China;India;Russia;United States;Canada;Australia', Commodity='0410000', Attribute='028')

Country     Australia     Canada      China      India     Russia United States
Commodity       Wheat      Wheat      Wheat      Wheat      Wheat         Wheat
Attribute  Production Production Production Production Production    Production
Frequency           A          A          A          A          A             A
1960-01-01     7450.0    14108.0    20960.0    10320.0        NaN       36877.0
1961-01-01     6727.0     7713.0    14250.0    10995.0        NaN       33557.0
1962-01-01     8353.0    15392.0    16665.0    12076.0        NaN       29719.0
1963-01-01     8925.0    19690.0    18475.0    10779.0        NaN       31216.0
1964-01-01    10037.0    16349.0    20840.0     9854.0        NaN       34917.0
...               ...        ...        ...        ...        ...           ...
2017-01-01    20941.0    30377.0   134334.0    98510.0    85167.0       47380.0
2018-01-01    17598.0    32352.0   131430.0    99870.0    71685.0       51306.0
2019-01-01    15200.0    32670.0   133590.0   103600.0    73610.0       52581.0
2020-01-01    33000.0    35183.0   134250.0   107860.0    85354.0       49691.0
2021-01-01    27000.0    32000.0   136000.0   108000.0    85000.0       50948.0

[62 rows x 6 columns]

In [ ]:
test_1 = knoema.get('USDAPSD2021May25', frequency='A', Country='China', Commodity='0410000', Attribute='028')

In [ ]:
test_1

Country         China
Commodity       Wheat
Attribute  Production
Frequency           A
1960-01-01    20960.0
1961-01-01    14250.0
1962-01-01    16665.0
1963-01-01    18475.0
1964-01-01    20840.0
...               ...
2017-01-01   134334.0
2018-01-01   131430.0
2019-01-01   133590.0
2020-01-01   134250.0
2021-01-01   136000.0

[62 rows x 1 columns]

In [ ]:
pais =["CG","CF","RW","GH","AG","SF","LY","EG","GU","LT","AO","CT","SO","UV","GB","TO","SL","LI","DJ","ER","KE","GA","CN","CV","IV","CM","ET","BY","ML","CD","DM","WZ","EK","RH","SU","MI","MZ","NG","PU","TZ","SG","UG","ZA","OD","MA","MP","SE","TS","BC","NI","MO","TP","MR","WA","KZ","JA","MG","PK","AM","BG","CE","AF","BT","TI","IN","TX","GG","KG","UZ","AJ","KN","MV","KS","NP","CH","AC","BB","GJ","SC","ST","CU","GT","DR","JM","CS","PN","HO","NU","BH","ES","TD","BF","HA","RQ","SZ","FR","LU","MT","BO","IT","SP","NA","PL","BE","BU","HU","SW","CZ","DA","PO","RO","AU","GR","LO","EN","EI","LH","LG","NO","RS","HR","UP","MD","MK","AL","SR","BK","RB","IC","FI","UK","SI","GE","CA","MX","US","TN","NH","WS","AS","NZ","PP","BP","FJ","HK","MC","TW","RP","MY","TH","SN","VM","LA","BM","BX","CB","ID","VE","BR","AR","CI","CO","PE","EC","PA","UY","BL","GY","NS","CY","TU","BA","YE","KU","MU","QA","IZ","IR","TC","IS","SY","JO","LE","SA"]

In [ ]:
set(pais)

{'AC',
 'AF',
 'AG',
 'AJ',
 'AL',
 'AM',
 'AO',
 'AR',
 'AS',
 'AU',
 'BA',
 'BB',
 'BC',
 'BE',
 'BF',
 'BG',
 'BH',
 'BK',
 'BL',
 'BM',
 'BO',
 'BP',
 'BR',
 'BT',
 'BU',
 'BX',
 'BY',
 'CA',
 'CB',
 'CD',
 'CE',
 'CF',
 'CG',
 'CH',
 'CI',
 'CM',
 'CN',
 'CO',
 'CS',
 'CT',
 'CU',
 'CV',
 'CY',
 'CZ',
 'DA',
 'DJ',
 'DM',
 'DR',
 'EC',
 'EG',
 'EI',
 'EK',
 'EN',
 'ER',
 'ES',
 'ET',
 'FI',
 'FJ',
 'FR',
 'GA',
 'GB',
 'GE',
 'GG',
 'GH',
 'GJ',
 'GR',
 'GT',
 'GU',
 'GY',
 'HA',
 'HK',
 'HO',
 'HR',
 'HU',
 'IC',
 'ID',
 'IN',
 'IR',
 'IS',
 'IT',
 'IV',
 'IZ',
 'JA',
 'JM',
 'JO',
 'KE',
 'KG',
 'KN',
 'KS',
 'KU',
 'KZ',
 'LA',
 'LE',
 'LG',
 'LH',
 'LI',
 'LO',
 'LT',
 'LU',
 'LY',
 'MA',
 'MC',
 'MD',
 'MG',
 'MI',
 'MK',
 'ML',
 'MO',
 'MP',
 'MR',
 'MT',
 'MU',
 'MV',
 'MX',
 'MY',
 'MZ',
 'NA',
 'NG',
 'NH',
 'NI',
 'NO',
 'NP',
 'NS',
 'NU',
 'NZ',
 'OD',
 'PA',
 'PE',
 'PK',
 'PL',
 'PN',
 'PO',
 'PP',
 'PU',
 'QA',
 'RB',
 'RH',
 'RO',
 'RP',
 'RQ',
 'RS',
 'RW',
 'SA',
 'SC',
 'SE',
 'SF',
 'SG',
 'SI',
 'SL',
 'SN',
 'SO',
 'SP',
 'SR',
 'ST',
 'SU',
 'SW',
 'SY',
 'SZ',
 'TC',
 'TD',
 'TH',
 'TI',
 'TN',
 'TO',
 'TP',
 'TS',
 'TU',
 'TW',
 'TX',
 'TZ',
 'UG',
 'UK',
 'UP',
 'US',
 'UV',
 'UY',
 'UZ',
 'VE',
 'VM',
 'WA',
 'WS',
 'WZ',
 'YE',
 'ZA'}

In [ ]:
paises = ["CG","CF","RW","GH","AG","SF","LY","EG","GU","LT","AO","CT","SO","UV","GB","TO","SL","LI","DJ","ER","KE","GA","CN","CV","IV","CM","ET","BY","ML","CD","DM","WZ","EK","RH","SU","MI","MZ","NG","PU","TZ","SG","UG","ZA","OD","MA","MP","SE","TS","BC","NI","MO","TP","MR","WA","KZ","JA","MG","PK","AM","BG","CE","AF","BT","TI","IN","TX","GG","KG","UZ","AJ","KN","MV","KS","NP","CH","AC","BB","GJ","SC","ST","CU","GT","DR","JM","CS","PN","HO","NU","BH","ES","TD","BF","HA","RQ","SZ","FR","LU","MT","BO","IT","SP","NA","PL","BE","BU","HU","SW","CZ","DA","PO","RO","AU","GR","LO","EN","EI","LH","LG","NO","RS","HR","UP","MD","MK","AL","SR","BK","RB","IC","FI","UK","SI","GE","CA","MX","US","TN","NH","WS","AS","NZ","PP","BP","FJ","HK","MC","TW","RP","MY","TH","SN","VM","LA","BM","BX","CB","ID","VE","BR","AR","CI","CO","PE","EC","PA","UY","BL","GY","NS","CY","TU","BA","YE","KU","MU","QA","IZ","IR","TC","IS","SY","JO","LE","SA"]

paises_sem_duplicatas = list(dict.fromkeys(paises))

In [ ]:
print(paises_sem_duplicatas)

['CG', 'CF', 'RW', 'GH', 'AG', 'SF', 'LY', 'EG', 'GU', 'LT', 'AO', 'CT', 'SO', 'UV', 'GB', 'TO', 'SL', 'LI', 'DJ', 'ER', 'KE', 'GA', 'CN', 'CV', 'IV', 'CM', 'ET', 'BY', 'ML', 'CD', 'DM', 'WZ', 'EK', 'RH', 'SU', 'MI', 'MZ', 'NG', 'PU', 'TZ', 'SG', 'UG', 'ZA', 'OD', 'MA', 'MP', 'SE', 'TS', 'BC', 'NI', 'MO', 'TP', 'MR', 'WA', 'KZ', 'JA', 'MG', 'PK', 'AM', 'BG', 'CE', 'AF', 'BT', 'TI', 'IN', 'TX', 'GG', 'KG', 'UZ', 'AJ', 'KN', 'MV', 'KS', 'NP', 'CH', 'AC', 'BB', 'GJ', 'SC', 'ST', 'CU', 'GT', 'DR', 'JM', 'CS', 'PN', 'HO', 'NU', 'BH', 'ES', 'TD', 'BF', 'HA', 'RQ', 'SZ', 'FR', 'LU', 'MT', 'BO', 'IT', 'SP', 'NA', 'PL', 'BE', 'BU', 'HU', 'SW', 'CZ', 'DA', 'PO', 'RO', 'AU', 'GR', 'LO', 'EN', 'EI', 'LH', 'LG', 'NO', 'RS', 'HR', 'UP', 'MD', 'MK', 'AL', 'SR', 'BK', 'RB', 'IC', 'FI', 'UK', 'SI', 'GE', 'CA', 'MX', 'US', 'TN', 'NH', 'WS', 'AS', 'NZ', 'PP', 'BP', 'FJ', 'HK', 'MC', 'TW', 'RP', 'MY', 'TH', 'SN', 'VM', 'LA', 'BM', 'BX', 'CB', 'ID', 'VE', 'BR', 'AR', 'CI', 'CO', 'PE', 'EC', 'PA', 'UY', 'BL', 'GY', 'NS', 'CY', 'TU', 'BA', 'YE', 'KU', 'MU', 'QA', 'IZ', 'IR', 'TC', 'IS', 'SY', 'JO', 'LE', 'SA']

In [ ]:
paises_1 = ["CG","CF","RW","GH","AG","SF","LY","EG","GU","LT","AO","CT","SO","UV","GB","TO","SL","LI","DJ","ER","KE","GA","CN","CV","IV","CM","ET","BY","ML","CD","DM","WZ","EK","RH","SU","MI","MZ","NG","PU","TZ","SG","UG","ZA","OD","MA","MP","SE","TS","BC","NI","MO","TP","MR","WA","KZ","JA","MG","PK","AM","BG","CE","AF","BT","TI","IN","TX","GG","KG","UZ","AJ","KN","MV","KS","NP","CH","AC","BB","GJ","SC","ST","CU","GT","DR","JM","CS","PN","HO","NU","BH","ES","TD","BF","HA","RQ","SZ","FR","LU","MT","BO","IT","SP","NA","PL","BE","BU","HU","SW","CZ","DA","PO","RO","AU","GR","LO","EN","EI","LH","LG","NO","RS","HR","UP","MD","MK","AL","SR","BK","RB","IC","FI","UK","SI","GE","CA","MX","US","TN","NH","WS","AS","NZ","PP","BP","FJ","HK","MC","TW","RP","MY","TH","SN","VM","LA","BM","BX","CB","ID","VE","BR","AR","CI","CO","PE","EC","PA","UY","BL","GY","NS","CY","TU","BA","YE","KU","MU","QA","IZ","IR","TC","IS","SY","JO","LE","SA"]

paises_sem_duplicatas_1 = list(set(paises))

print(paises_sem_duplicatas_1)

['UZ', 'GH', 'BK', 'TZ', 'WS', 'UY', 'EG', 'SL', 'KZ', 'CO', 'RH', 'CH', 'SI', 'GB', 'IV', 'NG', 'MO', 'CT', 'PU', 'GJ', 'EC', 'CY', 'SF', 'JO', 'BT', 'JM', 'BC', 'TC', 'GA', 'IC', 'SO', 'TS', 'GG', 'NU', 'IZ', 'KN', 'DR', 'NA', 'PO', 'RP', 'SR', 'FI', 'MP', 'CE', 'ES', 'HA', 'BX', 'HU', 'SY', 'NZ', 'AC', 'TN', 'SN', 'AU', 'LT', 'PP', 'HR', 'GT', 'SU', 'PA', 'WA', 'AF', 'IT', 'BH', 'PK', 'BP', 'AS', 'CI', 'RQ', 'BA', 'TX', 'DJ', 'SA', 'BR', 'MR', 'OD', 'NI', 'TO', 'FR', 'MT', 'CS', 'EI', 'AR', 'ZA', 'US', 'RO', 'GR', 'FJ', 'ID', 'MC', 'SP', 'ER', 'LA', 'UG', 'MD', 'SZ', 'LO', 'MI', 'CV', 'MY', 'BB', 'RW', 'HK', 'CB', 'CF', 'SG', 'LU', 'UK', 'CN', 'TU', 'SC', 'WZ', 'HO', 'TD', 'CA', 'GY', 'IS', 'DA', 'MG', 'GE', 'RB', 'ST', 'NH', 'TI', 'VM', 'BU', 'AM', 'TW', 'SW', 'BM', 'BE', 'NP', 'RS', 'CG', 'KE', 'PL', 'BL', 'LE', 'AO', 'MZ', 'CZ', 'JA', 'UP', 'GU', 'CM', 'MX', 'BO', 'ML', 'YE', 'CU', 'BF', 'KG', 'ET', 'LY', 'LG', 'MU', 'EN', 'CD', 'MK', 'LH', 'AG', 'UV', 'LI', 'AL', 'IN', 'NS', 'NO', 'MA', 'BG', 'TH', 'TP', 'DM', 'MV', 'PE', 'EK', 'PN', 'SE', 'KU', 'QA', 'IR', 'VE', 'AJ', 'KS', 'BY']

In [ ]:
import knoema

In [4]:
knoema_1 =knoema.get('USDAPSD2021May25', frequency='A', \
           Country='CG;CF;RW;GH;AG;SF;LY;EG;GU;LT;AO;SO;UV;GB;TO;SL;LI;DJ;ER;KE;CN;CV;IV;CM;ET;BY;ML;CD;DM;WZ;EK;RH;SU;MI;MZ;NG;PU;TZ;SG;UG;OD;MA;MP;SE;TS;BC;NI;MO;TP;MR;WA;KZ;JA;PK;AM;BG;CE;AF;BT;TI;IN;TX;KG;UZ;AJ', Commodity='0410000', Attribute='028')

           #GA;CN;CV;IV;CM;ET;BY;ML;CD;DM;WZ;EK;RH;SU;MI
           #MZ;NG;PU;TZ;SG;UG;ZA;OD;MA;MP;SE;TS;BC;
           #NI;MO;TP;MR;WA;KZ;JA;MG;PK;AM;BG;CE;AF;\
           #BT;TI;IN;TX;GG;KG;UZ;AJ;KN;MV;KS;NP;CH;

In [5]:
knoema_1

Country    Afghanistan    Algeria     Angola  ...     Uganda Uzbekistan   Zimbabwe
Commodity        Wheat      Wheat      Wheat  ...      Wheat      Wheat      Wheat
Attribute   Production Production Production  ... Production Production Production
Frequency            A          A          A  ...          A          A          A
1960-01-01      2279.0     1509.0        0.0  ...        NaN        NaN        1.0
1961-01-01      2279.0      686.0       20.0  ...        NaN        NaN        1.0
1962-01-01      2279.0     1507.0       20.0  ...        NaN        NaN        1.0
1963-01-01      1947.0     1590.0       20.0  ...        NaN        NaN        2.0
1964-01-01      2250.0     1162.0       13.0  ...        NaN        NaN        4.0
...                ...        ...        ...  ...        ...        ...        ...
2017-01-01      4281.0     2400.0        3.0  ...       22.0     6941.0      158.0
2018-01-01      3600.0     3940.0        3.0  ...       23.0     6000.0      170.0
2019-01-01      5000.0     3950.0        1.0  ...       24.0     6800.0       95.0
2020-01-01      5010.0     3900.0        3.0  ...       25.0     6510.0      180.0
2021-01-01      4400.0     3700.0        3.0  ...       25.0     6000.0      180.0

[62 rows x 54 columns]

In [ ]:
CT
GA
ZA





incluído =GB;TO;SL;LI;DJ;ER;KE;
incluído = GA;CN;CV;IV;CM;ET;BY;ML;CD;DM;WZ;EK;RH;SU;MI;
incluído = MZ;NG;PU;TZ;SG;UG;ZA;OD;MA;MP;SE;TS;BC;
incluiído =

GA;CN;CV;IV;CM;ET;BY;ML;CD;DM;WZ;EK;RH;SU;MI;\
           MZ;NG;PU;TZ;SG;UG;ZA;OD;MA;MP;SE;TS;BC;\
           NI;MO;TP;MR;WA;KZ;JA;MG;PK;AM;BG;CE;AF;\
           BT;TI;IN;TX;GG;KG;UZ;AJ;KN;MV;KS;NP;CH;\
           AC;BB;GJ;SC;ST;CU;GT;DR;JM;CS;PN;HO;NU;\
           BH;ES;TD;BF;HA;RQ;SZ;FR;LU;MT;BO;IT;SP;\
           NA;PL;BE;BU;HU;SW;CZ;DA;PO;RO;AU;GR;LO;\
           EN;EI;LH;LG;NO;RS;HR;UP;MD;MK;AL;SR;BK;\
           RB;IC;FI;UK;SI;GE;CA;MX;US;TN;NH;WS;AS;\
           NZ;PP;BP;FJ;HK;MC;TW;RP;MY;TH;SN;VM;LA;\
           BM;BX;CB;ID;VE;BR;AR;CI;CO;PE;EC;PA;UY;\
           BL;GY;NS;CY;TU;BA;YE;KU;MU;QA;IZ;IR;TC;\
           IS;SY;JO;LE;SA'













AO;ct;SO;UV;GB;TO;SL;LI;DJ;ER;KE;GA;CN;
           CV;IV;CM;ET;BY;ML;CD;DM;WZ;EK;RH;SU;MI'\

MZ;NG;PU;TZ;SG;UG;ZA;OD;MA;MP;SE;TS;BC;\
           NI;MO;TP;MR;WA;KZ;JA;MG;PK;AM;BG;CE;AF;\
           BT;TI;IN;TX;GG;KG;UZ;AJ;KN;MV;KS;NP;CH;\
           AC;BB;GJ;SC;ST;CU;GT;DR;JM;CS;PN;HO;NU;\
           BH;ES;TD;BF;HA;RQ;SZ;FR;LU;MT;BO;IT;SP;\
           NA;PL;BE;BU;HU;SW;CZ;DA;PO;RO;AU;GR;LO;\
           EN;EI;LH;LG;NO;RS;HR;UP;MD;MK;AL;SR;BK;\
           RB;IC;FI;UK;SI;GE;CA;MX;US;TN;NH;WS;AS;\
           NZ;PP;BP;FJ;HK;MC;TW;RP;MY;TH;SN;VM;LA;\
           BM;BX;CB;ID;VE;BR;AR;CI;CO;PE;EC;PA;UY;\
           BL;GY;NS;CY;TU;BA;YE;KU;MU;QA;IZ;IR;TC;\
           IS;SY;JO;LE;SA'

In [7]:
knoema_1.to_csv('knoema_1.csv')

In [9]:
knoema_2 =knoema.get('USDAPSD2021May25', frequency='A', \
           Country='KN;MV;KS;NP;CH;AC;BB;GJ;SC;ST;CU;GT;DR;JM;CS;PN;HO;NU', Commodity='0410000', Attribute='028')

In [10]:
knoema_2

Country      Barbados      China Costa Rica  ...      Nepal  Nicaragua     Panama
Commodity       Wheat      Wheat      Wheat  ...      Wheat      Wheat      Wheat
Attribute  Production Production Production  ... Production Production Production
Frequency           A          A          A  ...          A          A          A
1960-01-01        NaN    20960.0        0.0  ...      125.0        0.0        0.0
1961-01-01        NaN    14250.0        0.0  ...      135.0        0.0        0.0
1962-01-01        NaN    16665.0        0.0  ...      138.0        0.0        0.0
1963-01-01        NaN    18475.0        0.0  ...      138.0        0.0        0.0
1964-01-01        NaN    20840.0        0.0  ...      139.0        0.0        0.0
...               ...        ...        ...  ...        ...        ...        ...
2017-01-01        0.0   134334.0        0.0  ...     1949.0        0.0        0.0
2018-01-01        0.0   131430.0        0.0  ...     2006.0        0.0        0.0
2019-01-01        0.0   133590.0        0.0  ...     2200.0        0.0        0.0
2020-01-01        0.0   134250.0        0.0  ...     2210.0        0.0        0.0
2021-01-01        0.0   136000.0        0.0  ...     2100.0        0.0        0.0

[62 rows x 13 columns]

In [11]:
knoema_2.to_csv('knoema_2.csv')

In [14]:
knoema_3 =knoema.get('USDAPSD2021May25', frequency='A', \
           Country='BH;ES;TD;BF;HA;RQ;SZ;FR;LU;MT;BO;IT;SP;NA;PL;BE;BU;HU;SW;CZ;DA;PO;RO;AU;GR;LO;EN;EI;LH;LG;NO;RS;HR;UP;MD;MK;AL;SR;BK', Commodity='0410000', Attribute='028')

'BH;ES;TD;BF;HA;RQ;SZ;FR;LU;MT;BO;IT;SP;\
           NA;PL;BE;BU;HU;SW;CZ;DA;PO;RO;AU;GR;LO;\
           EN;EI;LH;LG;NO;RS;HR;UP;MD;MK;AL;SR;BK;\
           RB;IC;FI;UK;SI;GE;CA;MX;US;TN;NH;WS;AS;\
           NZ;PP;BP;FJ;HK;MC;TW;RP;MY;TH;SN;VM;LA;\
           BM;BX;CB;ID;VE;BR;AR;CI;CO;PE;EC;PA;UY;\
           BL;GY;NS;CY;TU;BA;YE;KU;MU;QA;IZ;IR;TC;\
           IS;SY;JO;LE;SA'

'BH;ES;TD;BF;HA;RQ;SZ;FR;LU;MT;BO;IT;SP;           NA;PL;BE;BU;HU;SW;CZ;DA;PO;RO;AU;GR;LO;           EN;EI;LH;LG;NO;RS;HR;UP;MD;MK;AL;SR;BK;           RB;IC;FI;UK;SI;GE;CA;MX;US;TN;NH;WS;AS;           NZ;PP;BP;FJ;HK;MC;TW;RP;MY;TH;SN;VM;LA;           BM;BX;CB;ID;VE;BR;AR;CI;CO;PE;EC;PA;UY;           BL;GY;NS;CY;TU;BA;YE;KU;MU;QA;IZ;IR;TC;           IS;SY;JO;LE;SA'

In [15]:
knoema_3

Country       Albania  Australia  ...   Slovakia    Ukraine
Commodity       Wheat      Wheat  ...      Wheat      Wheat
Attribute  Production Production  ... Production Production
Frequency           A          A  ...          A          A
1960-01-01       64.0     7450.0  ...        NaN        NaN
1961-01-01       98.0     6727.0  ...        NaN        NaN
1962-01-01      146.0     8353.0  ...        NaN        NaN
1963-01-01       62.0     8925.0  ...        NaN        NaN
1964-01-01      124.0    10037.0  ...        NaN        NaN
...               ...        ...  ...        ...        ...
2017-01-01      275.0    20941.0  ...        NaN    26981.0
2018-01-01      240.0    17598.0  ...        NaN    25057.0
2019-01-01      233.0    15200.0  ...        NaN    29171.0
2020-01-01      265.0    33000.0  ...        NaN    25420.0
2021-01-01      265.0    27000.0  ...        NaN    29000.0

[62 rows x 26 columns]

In [16]:
knoema_3.to_csv('knoema_3.csv')

In [19]:


knoema_4 =knoema.get('USDAPSD2021May25', frequency='A', \
           Country='RB;IC;FI;UK;SI;GE;CA;MX;US;TN;NH;WS;AS;NZ;PP;BP;FJ;HK;MC;TW;RP;MY;TH;SN;VM;LA', Commodity='0410000', Attribute='028')



#RB;IC;FI;UK;SI;GE;CA;MX;US;TN;NH;WS;AS;\
           #NZ;PP;BP;FJ;HK;MC;TW;RP;MY;TH;SN;VM;LA;\
           #BM;BX;CB;ID;VE;BR;AR;CI;CO;PE;EC;PA;UY;\
           #BL;GY;NS;CY;TU;BA;YE;KU;MU;QA;IZ;IR;TC;\
           #IS;SY;JO;LE;SA'

In [20]:
knoema_4

Country     Australia     Canada  ... United States    Vietnam
Commodity       Wheat      Wheat  ...         Wheat      Wheat
Attribute  Production Production  ...    Production Production
Frequency           A          A  ...             A          A
1960-01-01     7450.0    14108.0  ...       36877.0        NaN
1961-01-01     6727.0     7713.0  ...       33557.0        NaN
1962-01-01     8353.0    15392.0  ...       29719.0        NaN
1963-01-01     8925.0    19690.0  ...       31216.0        0.0
1964-01-01    10037.0    16349.0  ...       34917.0        0.0
...               ...        ...  ...           ...        ...
2017-01-01    20941.0    30377.0  ...       47380.0        0.0
2018-01-01    17598.0    32352.0  ...       51306.0        0.0
2019-01-01    15200.0    32670.0  ...       52581.0        0.0
2020-01-01    33000.0    35183.0  ...       49691.0        0.0
2021-01-01    27000.0    32000.0  ...       50948.0        0.0

[62 rows x 18 columns]

In [21]:
knoema_4.to_csv('knoema_4.csv')

In [22]:

knoema_5 =knoema.get('USDAPSD2021May25', frequency='A', \
           Country='BM;BX;CB;ID;VE;BR;AR;CI;CO;PE;EC;PA;UY;BL;GY;NS;CY;TU;BA;YE;KU;MU;QA;IZ;IR;TC;IS;SY;JO;LE;SA', Commodity='0410000', Attribute='028')

In [23]:
knoema_5

Country     Argentina    Bahrain    Bolivia  ...    Uruguay  Venezuela      Yemen
Commodity       Wheat      Wheat      Wheat  ...      Wheat      Wheat      Wheat
Attribute  Production Production Production  ... Production Production Production
Frequency           A          A          A  ...          A          A          A
1960-01-01     3960.0        NaN       68.0  ...      413.0        1.0        NaN
1961-01-01     5725.0        NaN       35.0  ...      372.0        1.0        NaN
1962-01-01     5700.0        NaN       40.0  ...      452.0        1.0        NaN
1963-01-01     8940.0        NaN       55.0  ...      237.0        1.0        NaN
1964-01-01    11260.0        NaN       57.0  ...      646.0        1.0        NaN
...               ...        ...        ...  ...        ...        ...        ...
2017-01-01    18500.0        0.0      302.0  ...      440.0        0.0      150.0
2018-01-01    19500.0        0.0      237.0  ...      728.0        0.0      140.0
2019-01-01    19780.0        0.0      311.0  ...      776.0        0.0      140.0
2020-01-01    17630.0        0.0      305.0  ...      745.0        0.0      138.0
2021-01-01    20500.0        0.0      315.0  ...      900.0        0.0      125.0

[62 rows x 25 columns]

In [24]:
knoema_5.to_csv('knoema_5.csv')

In [25]:
knoema_6 =knoema.get('USDAPSD2021May25', frequency='A', \
           Country='CT;GA;ZA;MG;KG;GG', Commodity='0410000', Attribute='028')

In [26]:
knoema_6

Country         Gabon    Georgia Kyrgyzstan Madagascar South Africa
Commodity       Wheat      Wheat      Wheat      Wheat        Wheat
Attribute  Production Production Production Production   Production
Frequency           A          A          A          A            A
1960-01-01        0.0        NaN        NaN        0.0        769.0
1961-01-01        0.0        NaN        NaN        0.0        871.0
1962-01-01        0.0        NaN        NaN        0.0        705.0
1963-01-01        0.0        NaN        NaN        0.0        880.0
1964-01-01        0.0        NaN        NaN        0.0       1060.0
...               ...        ...        ...        ...          ...
2017-01-01        0.0       98.0      601.0        0.0       1535.0
2018-01-01        0.0      107.0      616.0        0.0       1868.0
2019-01-01        0.0      100.0      590.0        0.0       1535.0
2020-01-01        0.0       94.0      559.0        0.0       2120.0
2021-01-01        0.0      105.0      530.0        0.0       1800.0

[62 rows x 5 columns]

In [27]:
knoema_6.to_csv('knoema_6.csv')

In [28]:
import pandas as pd

In [29]:
all_docs_knoema = pd.concat([knoema_1, knoema_2,knoema_3,knoema_4,knoema_5,knoema_6])

In [30]:
all_docs_knoema

Country    Afghanistan    Albania    Algeria  ...    Vietnam      Yemen   Zimbabwe
Commodity        Wheat      Wheat      Wheat  ...      Wheat      Wheat      Wheat
Attribute   Production Production Production  ... Production Production Production
Frequency            A          A          A  ...          A          A          A
1960-01-01      2279.0        NaN     1509.0  ...        NaN        NaN        1.0
1961-01-01      2279.0        NaN      686.0  ...        NaN        NaN        1.0
1962-01-01      2279.0        NaN     1507.0  ...        NaN        NaN        1.0
1963-01-01      1947.0        NaN     1590.0  ...        NaN        NaN        2.0
1964-01-01      2250.0        NaN     1162.0  ...        NaN        NaN        4.0
...                ...        ...        ...  ...        ...        ...        ...
2017-01-01         NaN        NaN        NaN  ...        NaN        NaN        NaN
2018-01-01         NaN        NaN        NaN  ...        NaN        NaN        NaN
2019-01-01         NaN        NaN        NaN  ...        NaN        NaN        NaN
2020-01-01         NaN        NaN        NaN  ...        NaN        NaN        NaN
2021-01-01         NaN        NaN        NaN  ...        NaN        NaN        NaN

[372 rows x 126 columns]

In [43]:
countries_level_0 = all_docs_knoema.columns.get_level_values(0)

In [44]:
countries_level_0

Index(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia',
       'Australia', 'Azerbaijan', 'Bahrain', 'Bangladesh',
       ...
       'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Uzbekistan', 'Venezuela', 'Vietnam', 'Yemen', 'Zimbabwe'],
      dtype='object', name='Country', length=126)

In [45]:
countries_level_1 = all_docs_knoema.columns.get_level_values(1)

In [46]:
countries_level_1

Index(['Wheat', 'Wheat', 'Wheat', 'Wheat', 'Wheat', 'Wheat', 'Wheat', 'Wheat',
       'Wheat', 'Wheat',
       ...
       'Wheat', 'Wheat', 'Wheat', 'Wheat', 'Wheat', 'Wheat', 'Wheat', 'Wheat',
       'Wheat', 'Wheat'],
      dtype='object', name='Commodity', length=126)

In [47]:
countries_level_2 = all_docs_knoema.columns.get_level_values(2)

In [48]:
countries_level_2

Index(['Production', 'Production', 'Production', 'Production', 'Production',
       'Production', 'Production', 'Production', 'Production', 'Production',
       ...
       'Production', 'Production', 'Production', 'Production', 'Production',
       'Production', 'Production', 'Production', 'Production', 'Production'],
      dtype='object', name='Attribute', length=126)

In [49]:
all_docs_knoema.columns.to_flat_index()

Index([         ('Afghanistan', 'Wheat', 'Production', 'A'),
                    ('Albania', 'Wheat', 'Production', 'A'),
                    ('Algeria', 'Wheat', 'Production', 'A'),
                     ('Angola', 'Wheat', 'Production', 'A'),
                  ('Argentina', 'Wheat', 'Production', 'A'),
                    ('Armenia', 'Wheat', 'Production', 'A'),
                  ('Australia', 'Wheat', 'Production', 'A'),
                 ('Azerbaijan', 'Wheat', 'Production', 'A'),
                    ('Bahrain', 'Wheat', 'Production', 'A'),
                 ('Bangladesh', 'Wheat', 'Production', 'A'),
       ...
                    ('Ukraine', 'Wheat', 'Production', 'A'),
       ('United Arab Emirates', 'Wheat', 'Production', 'A'),
             ('United Kingdom', 'Wheat', 'Production', 'A'),
              ('United States', 'Wheat', 'Production', 'A'),
                    ('Uruguay', 'Wheat', 'Production', 'A'),
                 ('Uzbekistan', 'Wheat', 'Production', 'A'),
                  ('Venezuela', 'Wheat', 'Production', 'A'),
                    ('Vietnam', 'Wheat', 'Production', 'A'),
                      ('Yemen', 'Wheat', 'Production', 'A'),
                   ('Zimbabwe', 'Wheat', 'Production', 'A')],
      dtype='object', length=126)

In [51]:
countries_level_0.to_list()

['Afghanistan',
 'Albania',
 'Algeria',
 'Angola',
 'Argentina',
 'Armenia',
 'Australia',
 'Azerbaijan',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Brazil',
 'Bulgaria',
 'Burkina',
 'Cameroon',
 'Canada',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Congo (Brazzaville)',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Fiji',
 'Gabon',
 'Georgia',
 'Ghana',
 'Guatemala',
 'Guinea',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Korea, North',
 'Korea, South',
 'Kuwait',
 'Kyrgyzstan',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Lithuania',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Mali',
 'Malta',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Mozambique',
 'Namibia',
 'Nepal',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'North Macedonia',
 'Norway',
 'Pakistan',
 'Panama',
 'Papua New Guinea',
 'Peru',
 'Philippines',
 'Poland',
 'Romania',
 'Russia',
 'Rwanda',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Serbia and Montenegro',
 'Sierra Leone',
 'Slovakia',
 'Slovenia',
 'Somalia',
 'South Africa',
 'Sri Lanka',
 'Sudan',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zimbabwe']

In [54]:
knoema_7 =knoema.get('USDAPSD2021May25', frequency='A', \
           Country='Cape Verde', Commodity='0410000', Attribute='028')

ValueError: ignored