<a href="https://colab.research.google.com/github/Renata-Thomazelli/mentoria2021/blob/main/tratando_doc_csv_tasmin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color='blue'>**Analisando Temperatura média**<font>

**Analisando Temperatura média**


---

##Importing the Data

---

In [ ]:
# Importing Drive
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#Importing the packages 
import pandas as pd
import numpy as np
import chardet
import missingno as msno
import matplotlib.pyplot as plt
%matplotlib inline

<font color='blue'>  Reading CSV  

Reading CSV

In [ ]:
file_path ='/content/drive/MyDrive/Temperatura_Precipitacao_analises/limpos/quartile_for_year/'


file = "tasmin_seasons_for_year_consolidado.csv"

In [ ]:
with open(f"{file_path}{file}", 'rb') as encoding:
    r_encoding = chardet.detect(encoding.read(100000))
r_encoding

{'confidence': 1.0, 'encoding': 'ascii', 'language': ''}

In [ ]:

with open (f"{file_path}{file}",'r',encoding=r_encoding['encoding']) as arquivo :
  df_tasmin = pd.read_csv(arquivo)

<font color='blue'> DataFrame

In [ ]:
df_tasmin

     year   min    25%    50%    75%   max    country iso3    tipo
0    1960  -3.4   0.25   6.25  11.32  14.5     Turkey  TUR  tasmin
1    1961  -4.7  -0.68   5.60   9.92  15.0     Turkey  TUR  tasmin
2    1962  -3.8   1.23   6.05  11.28  15.7     Turkey  TUR  tasmin
3    1963  -2.2  -0.68   5.85  11.52  15.0     Turkey  TUR  tasmin
4    1964 -10.3   0.07   4.30  10.55  14.3     Turkey  TUR  tasmin
..    ...   ...    ...    ...    ...   ...        ...  ...     ...
849  2016  21.3  21.50  21.80  22.02  22.3  Indonesia  IDN  tasmin
850  2017  20.9  21.28  21.70  21.80  22.0  Indonesia  IDN  tasmin
851  2018  21.1  21.20  21.45  21.70  21.8  Indonesia  IDN  tasmin
852  2019  20.8  21.30  21.75  21.92  22.3  Indonesia  IDN  tasmin
853  2020  21.0  21.40  21.65  21.95  22.2  Indonesia  IDN  tasmin

[854 rows x 9 columns]

In [ ]:
colunas = [c.strip().lower().replace("50%","tasmin") for c in df_tasmin.columns]
df_tasmin.columns = colunas

In [ ]:
df_tasmin

     year   min    25%  tasmin    75%   max    country iso3    tipo
0    1960  -3.4   0.25    6.25  11.32  14.5     Turkey  TUR  tasmin
1    1961  -4.7  -0.68    5.60   9.92  15.0     Turkey  TUR  tasmin
2    1962  -3.8   1.23    6.05  11.28  15.7     Turkey  TUR  tasmin
3    1963  -2.2  -0.68    5.85  11.52  15.0     Turkey  TUR  tasmin
4    1964 -10.3   0.07    4.30  10.55  14.3     Turkey  TUR  tasmin
..    ...   ...    ...     ...    ...   ...        ...  ...     ...
849  2016  21.3  21.50   21.80  22.02  22.3  Indonesia  IDN  tasmin
850  2017  20.9  21.28   21.70  21.80  22.0  Indonesia  IDN  tasmin
851  2018  21.1  21.20   21.45  21.70  21.8  Indonesia  IDN  tasmin
852  2019  20.8  21.30   21.75  21.92  22.3  Indonesia  IDN  tasmin
853  2020  21.0  21.40   21.65  21.95  22.2  Indonesia  IDN  tasmin

[854 rows x 9 columns]

In [ ]:
df_tasmin_mediana = pd.pivot_table(df_tasmin, values =['tasmin'], columns=['iso3'], index='year')

In [ ]:
df_tasmin_mediana

     tasmin                            ...
iso3    AUS    BRA    CAN   CHN   DEU  ...    IND    PHL    RUS   TUR   USA
year                                   ...
1960  14.75  20.05 -11.45  0.15  4.70  ...  19.45  21.15 -12.20  6.25  0.55
1961  15.85  20.45 -12.60  1.25  6.25  ...  19.50  20.95 -11.45  5.60 -0.65
1962  14.55  19.90 -11.45  0.30  4.40  ...  19.25  21.05 -10.50  6.05  1.20
1963  14.80  20.40 -10.35  0.50  4.55  ...  19.45  20.75 -11.25  5.85  1.35
1964  14.70  19.70 -12.65  1.80  4.10  ...  20.10  21.20 -12.80  4.30  0.00
...     ...    ...    ...   ...   ...  ...    ...    ...    ...   ...   ...
2016  15.50  21.35 -11.00  2.65  4.60  ...  20.90  22.55  -8.30  6.65  2.80
2017  15.65  21.10 -11.00  2.40  5.45  ...  21.15  22.05  -8.40  5.25  2.35
2018  16.50  21.05 -13.00  2.05  6.55  ...  20.60  22.10  -7.35  7.35  1.25
2019  16.10  21.30 -11.15  2.75  5.35  ...  20.60  22.50  -7.85  6.55  1.65
2020  16.25  21.25 -12.35  1.70  5.80  ...  20.50  22.45  -7.00  6.55  0.90

[61 rows x 14 columns]

In [ ]:
df_tasmin_mediana =df_tasmin_mediana.swaplevel(i=-2,j=-1,axis=1)

In [ ]:
df_tasmin_mediana

iso3    AUS    BRA    CAN    CHN    DEU  ...    IND    PHL    RUS    TUR    USA
     tasmin tasmin tasmin tasmin tasmin  ... tasmin tasmin tasmin tasmin tasmin
year                                     ...
1960  14.75  20.05 -11.45   0.15   4.70  ...  19.45  21.15 -12.20   6.25   0.55
1961  15.85  20.45 -12.60   1.25   6.25  ...  19.50  20.95 -11.45   5.60  -0.65
1962  14.55  19.90 -11.45   0.30   4.40  ...  19.25  21.05 -10.50   6.05   1.20
1963  14.80  20.40 -10.35   0.50   4.55  ...  19.45  20.75 -11.25   5.85   1.35
1964  14.70  19.70 -12.65   1.80   4.10  ...  20.10  21.20 -12.80   4.30   0.00
...     ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
2016  15.50  21.35 -11.00   2.65   4.60  ...  20.90  22.55  -8.30   6.65   2.80
2017  15.65  21.10 -11.00   2.40   5.45  ...  21.15  22.05  -8.40   5.25   2.35
2018  16.50  21.05 -13.00   2.05   6.55  ...  20.60  22.10  -7.35   7.35   1.25
2019  16.10  21.30 -11.15   2.75   5.35  ...  20.60  22.50  -7.85   6.55   1.65
2020  16.25  21.25 -12.35   1.70   5.80  ...  20.50  22.45  -7.00   6.55   0.90

[61 rows x 14 columns]

In [ ]:
df_tasmin_mediana.index.name=None

In [ ]:
df_tasmin_mediana

iso3    AUS    BRA    CAN    CHN    DEU  ...    IND    PHL    RUS    TUR    USA
     tasmin tasmin tasmin tasmin tasmin  ... tasmin tasmin tasmin tasmin tasmin
1960  14.75  20.05 -11.45   0.15   4.70  ...  19.45  21.15 -12.20   6.25   0.55
1961  15.85  20.45 -12.60   1.25   6.25  ...  19.50  20.95 -11.45   5.60  -0.65
1962  14.55  19.90 -11.45   0.30   4.40  ...  19.25  21.05 -10.50   6.05   1.20
1963  14.80  20.40 -10.35   0.50   4.55  ...  19.45  20.75 -11.25   5.85   1.35
1964  14.70  19.70 -12.65   1.80   4.10  ...  20.10  21.20 -12.80   4.30   0.00
...     ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
2016  15.50  21.35 -11.00   2.65   4.60  ...  20.90  22.55  -8.30   6.65   2.80
2017  15.65  21.10 -11.00   2.40   5.45  ...  21.15  22.05  -8.40   5.25   2.35
2018  16.50  21.05 -13.00   2.05   6.55  ...  20.60  22.10  -7.35   7.35   1.25
2019  16.10  21.30 -11.15   2.75   5.35  ...  20.60  22.50  -7.85   6.55   1.65
2020  16.25  21.25 -12.35   1.70   5.80  ...  20.50  22.45  -7.00   6.55   0.90

[61 rows x 14 columns]

In [ ]:
caminho ='/content/drive/MyDrive/Temperatura_Precipitacao_analises/limpos/'
nome = 'df_tasmin_mediana.csv'
df_tasmin_mediana.to_csv(f"{caminho}{nome}")